# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_auto_20170218_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='description_internal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_notify',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='sensor_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='industry_in_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='oven_in_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='postalcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='street_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='street_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='traffic_in_area',
            field=models.IntegerField(null=True),
        ),
    ]
